### ISSUE TITLE
API Auth Error

### ISSUE THREAD

**Issue by cdnicoll** [Teamwork/github-sync#4]
When running the action im getting

`{"CONTENT":{"ERRORS":["Invalid token or token version"]}}`

I've setup both TEAMWORK_URI and TEAMWORK_API_TOKEN within my secrets, leaving GITHUB_TOKEN. I've also followed the setup instructions here: https://developer.teamwork.com/guides/api-key-url/ 

Is there anything else I might be missing?

**Comment by miguelbemartin** [comment]
Hey @cdnicoll, thanks for taking the time to open an issue for us.

Here at Teamwork, we are preparing a new way to generate the "API TOKEN" by using our [developer portal](https://developer.teamwork.com/guides/developer-portal/) in order to make it easier for the future. 

I will create a PR adding support to the API TOKEN you are trying to use.

**Comment by miguelbemartin** [comment]
Hey @cdnicoll, could you try again and confirm it is working now?

**Comment by cdnicoll** [comment]
@miguelbemartin It is. Thank you for the quick reply and fix.

It looks like comments are coming through as `[https://github.com/XXXX/<PROJECT>/pull/8](https://github.com/XXXX/<PROJECT>/pull/8)` on Teamwork side, but thats nothing major. It can be tracked in another issue if need be.

**Comment by miguelbemartin** [comment]
@cdnicoll Thanks again for your feedback. Could you open an issue with the details of the problem?
