### ISSUE TITLE
Option to prevent tasks being marked complete

### ISSUE THREAD

**Issue by isaac-jordan** [Teamwork/github-sync#63]
**Is your feature request related to a problem? Please describe.**
Would it be possible for there to be an option to prevent this action from marking Teamwork cards as complete when a PR is merged?

I don't think in our use-case (and probably many others) that there is an exact one-to-one mapping between Teamwork cards and single PRs - I'd prefer to manually complete the card when everything is merged and deployed.

**Describe the solution you'd like**
It would be useful if there was a config option for the action to disable this, e.g. `mark_as_complete: false` (fine if it defaults to true, if you want to retain the current behaviour).

**Comment by ripexz** [comment]
This action doesn't mark tasks as complete, I expect you most likely have configured a board column for tasks to be moved to with `BOARD_COLUMN_OPENED`/`BOARD_COLUMN_MERGED`/`BOARD_COLUMN_CLOSED` values, and the chosen board columns have a trigger/automation configured to mark tasks as complete when it's moved into it.

See https://support.teamwork.com/projects/automations/board-column-automations for more details - you can also add a condition to the automation to skip it if it has specific tags so that might work for your use-case here.

On the off-chance your Teamwork account still uses legacy board triggers, see "Auto complete" under https://support.teamwork.com/projects/board-view/board-view-triggers

**Comment by isaac-jordan** [comment]
Ah, yes you are correct! Thanks for that - I'm still learning about how Teamwork works :)
